variables:
  IMAGE_NAME: ankem123/football-app-1.0
  IMAGE_TAG: React Native

stages:
  - test
  - build
  - deploy

run_tests:
  stage: test
  image: React Native
  before_script: React
  script: 
    -  make test

.build:
  stage: build
  image: docker:20.10.16
  services: 
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:IMAGE_TAG .

build-dev:
  extends: .build
  only: 
    - main
